In [4]:
import os
print(os.getcwd())

c:\temp1\djangoTest

In [ ]:
``` mysql
SELECT
t1.name as name1,
t1.sectorAzimuth as sectorAzimuth1,
t1.enodeB as enodeB1,
t2.name as name2,
t2.sectorAzimuth as sectorAzimuth2,
t2.enodeB as enodeB2,
CONCAT(t1.name,"_",t2.name) AS CoverageRelationId
FROM
(
SELECT
o1.name,
right(o1.name,1) as sectorAzimuth,
o2.name as enodeB
FROM
c_cell cc
LEFT JOIN
OBJECTS o1
on o1.int_id= cc.int_id
LEFT JOIN
OBJECTS o2
on o2.int_id= o1.parent_int_id
)t1,
(
SELECT
o1.name,
right(o1.name,1) as sectorAzimuth,
o2.name as enodeB
FROM
c_cell cc
LEFT JOIN
OBJECTS o1
on o1.int_id= cc.int_id
LEFT JOIN
OBJECTS o2
on o2.int_id= o1.parent_int_id
)t2
where 
(
t1.enodeB=t2.enodeB
AND
t1.sectorAzimuth='U'
AND
t2.sectorAzimuth='X'
)
OR
(
t1.enodeB=t2.enodeB
AND
t1.sectorAzimuth='X'
AND
t2.sectorAzimuth='U'
)
OR
(
t1.enodeB=t2.enodeB
AND
t1.sectorAzimuth='Y'
AND
t2.sectorAzimuth='V'
)
OR
(
t1.enodeB=t2.enodeB
AND
t1.sectorAzimuth='V'
AND
t2.sectorAzimuth='Y'
)
OR
(
t1.enodeB=t2.enodeB
AND
t1.sectorAzimuth='Y'
AND
t2.sectorAzimuth='V'
)
OR
(
t1.enodeB=t2.enodeB
AND
t1.sectorAzimuth='Z'
AND
t2.sectorAzimuth='W'
)
OR
(
t1.enodeB=t2.enodeB
AND
t1.sectorAzimuth='W'
AND
t2.sectorAzimuth='Z'
);
```