In [1]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
#df1 = pd.read_excel('4G_L17_Pack4_DUAC_optimized_roply_L5MA2021C.xlsx')
df = pd.read_excel('4G_L17_Pack4_DUAC_optimized_roply_L5MA2021C.xlsx', sheet_name='PACK4_DUAC-DATA')
#print("Column headings:")
#print(df.columns)

In [2]:
import os
os.getcwd()
df1 = pd.read_excel('4G_L17_Pack4_DUAC_optimized_roply_L5MA2021C.xlsx', None)
df1.keys()

odict_keys(['Availability', 'Accessibility', 'Retainability', 'Interferences', 'DL Integrity', 'UL Integrity', 'Mobility', 'CQI&Users', 'Connected Users Licenses', 'System Load', 'Capacity', 'PACK4_DUAC', 'PACK4_DUAC-DATA', 'PACK4_DLC', 'PACK4_DLC-DATA', 'PACK4_PSS', 'PACK4_PSS-DATA', 'DATA_ERBS', 'PACK4_DUAC-DATA_ERBS', 'DATA_DAY_CLUSTER', 'DATA_DAY_ERBS', 'DATA_DAY_EUTRANCELL', 'DATA_HOUR_CLUSTER', 'DATA_HOUR_ERBS', 'DATA_HOUR_EUTRANCELL', 'DUAC_OPT_DAY_CLUSTER', 'DUAC_OPT_DAY_ERBS', 'DUAC_OPT_DAY_EUTRANCELL', 'DUAC_OPT_HOUR_CLUSTER', 'DUAC_OPT_HOUR_ERBS', 'DUAC_OPT_HOUR_EUTRANCELL', 'Report 32'])

In [3]:
df

,Unnamed: 0,_Date,_Hour,DUAC_CCE utilization Cell (avg),DUAC_Cell Handover Rejection Rate,DUAC_Cell RRC Connection Establishment Fail Rate,DUAC_Cell RRC Connection Reestablishment Fail Rate,DUAC_DL BB Cap utilization BB module (avg),DUAC_DL PRB BB mod (avg),DUAC_DL PRB Cell (avg),DUAC_DL SE utilization BB module (avg),DUAC_DL SE utilization Cell (avg),DUAC_Inc HO Rejects,DUAC_RRC Conn Rejects,DUAC_RRC Reestab Rejects,DUAC_UL BB Cap utilization BB module (avg),DUAC_UL PRB BB mod (avg),DUAC_UL PRB Cell (avg),DUAC_UL SE utilization BB module (avg),DUAC_UL SE utilization Cell (avg)
0,NaN,2018-10-07,0,3.010648,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.552083,2.500000,2.608889
1,NaN,2018-10-07,1,2.604398,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.501250,2.500000,2.501343
2,NaN,2018-10-07,2,2.644306,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.511620,2.500000,2.535370
3,NaN,2018-10-07,3,2.523102,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.500000
4,NaN,2018-10-07,4,2.518935,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.500000
5,NaN,2018-10-07,5,2.502731,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500926,2.500000,2.500000
6,NaN,2018-10-07,6,2.500694,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.500000
7,NaN,2018-10-07,7,2.534861,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.503426
8,NaN,2018-10-07,8,2.519444,0,0.000000,0,2.500000,2.500000,2.503704,2.500000,2.500000,0,0,0,2.500000,2.5,2.543796,2.500000,2.501296
9,NaN,2018-10-07,9,2.720648,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.512917,2.500000,2.543287
10,NaN,2018-10-07,10,2.709074,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.526204,2.500000,2.540417
11,NaN,2018-10-07,11,2.703194,0,0.000000,0,2.500000,2.500000,2.503102,2.500000,2.500000,0,0,0,2.500000,2.5,2.549259,2.500000,2.527500
12,NaN,2018-10-07,12,2.963148,0,0.000000,0,2.500000,2.500000,2.515231,2.500000,2.500000,0,0,0,2.500000,2.5,2.622500,2.500000,2.555880
13,NaN,2018-10-07,13,3.931852,0,0.000000,0,2.500000,2.500000,2.965648,2.500000,2.500000,0,0,0,2.500000,2.5,3.096944,2.500000,2.776620
14,NaN,2018-10-07,14,5.424907,0,0.000000,0,2.500000,2.500000,4.443056,2.500000,2.508148,0,0,0,2.503194,2.5,4.087269,2.500000,3.656065
15,NaN,2018-10-07,15,22.419398,0,0.372901,0,4.711389,3.921250,28.076759,3.528333,6.649630,0,363,0,5.452778,2.5,13.325278,6.455139,11.902222
16,NaN,2018-10-07,16,31.276250,0,0.000000,0,2.882917,2.599444,25.636806,2.523472,5.890648,0,0,0,7.273194,2.5,20.435648,10.048194,17.831019
17,NaN,2018-10-07,17,29.494028,0,0.000000,0,3.087500,2.955833,28.590648,2.721806,6.486991,0,0,0,5.915694,2.5,17.329028,9.183611,15.757361
18,NaN,2018-10-07,18,20.677917,0,2.680063,0,5.540278,3.896389,27.820926,3.754722,6.586898,0,2294,0,5.405139,2.5,12.269491,6.253611,11.789537
19,NaN,2018-10-07,19,3.833565,0,0.000000,0,2.500000,2.500000,3.136944,2.500000,2.500000,0,0,0,2.500000,2.5,3.029444,2.500000,2.845370
20,NaN,2018-10-07,20,2.878750,0,0.000000,0,2.500000,2.500000,2.502037,2.500000,2.500000,0,0,0,2.500000,2.5,2.533704,2.500000,2.573009
21,NaN,2018-10-07,21,2.710972,0,0.000000,0,2.500000,2.500000,2.508194,2.500000,2.500000,0,0,0,2.500000,2.5,2.726759,2.500000,2.526343
22,NaN,2018-10-07,22,2.898981,0,0.000000,0,2.500000,2.500000,2.500370,2.500000,2.500000,0,0,0,2.500000,2.5,2.541620,2.500000,2.587315
23,NaN,2018-10-07,23,2.545093,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.521389,2.500000,2.517500
24,NaN,2018-10-08,0,2.557778,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.522500,2.500000,2.501296
25,NaN,2018-10-08,1,2.556667,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.511204
26,NaN,2018-10-08,2,2.510093,0,0.000000,0,2.500000,2.500000,2.500880,2.500000,2.500000,0,0,0,2.500000,2.5,2.539444,2.500000,2.500000
27,NaN,2018-10-08,3,2.524676,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.500556
28,NaN,2018-10-08,4,2.525046,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.500000
29,NaN,2018-10-08,5,2.531806,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.500000
30,NaN,2018-10-08,6,2.528287,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.500000
31,NaN,2018-10-08,7,2.599954,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.500000,2.500000,2.510648
32,NaN,2018-10-08,8,2.903472,0,0.000000,0,2.500000,2.500000,2.537778,2.500000,2.500000,0,0,0,2.523750,2.5,2.736065,2.500000,2.590417
33,NaN,2018-10-08,9,3.153009,0,0.000000,0,2.500000,2.500000,2.500972,2.500000,2.500000,0,0,0,2.500000,2.5,2.600000,2.500000,2.680093
34,NaN,2018-10-08,10,2.765556,0,0.000000,0,2.500000,2.500000,2.500370,2.500000,2.500000,0,0,0,2.500000,2.5,2.532593,2.500000,2.528565
35,NaN,2018-10-08,11,2.732083,0,0.000000,0,2.500000,2.500000,2.501806,2.500000,2.500000,0,0,0,2.500000,2.5,2.529954,2.500000,2.538704
36,NaN,2018-10-08,12,3.034907,0,0.000000,0,2.500000,2.500000,2.503102,2.500000,2.500000,0,0,0,2.500000,2.5,2.612870,2.500000,2.594722
37,NaN,2018-10-08,13,2.783565,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.526250,2.500000,2.561898
38,NaN,2018-10-08,14,3.370926,0,0.000000,0,2.500000,2.500000,2.504352,2.500000,2.500000,0,0,0,2.500000,2.5,2.615926,2.500000,2.691296
39,NaN,2018-10-08,15,3.196806,0,0.000000,0,2.500000,2.500000,2.502222,2.500000,2.500000,0,0,0,2.500000,2.5,2.575139,2.500000,2.673333
40,NaN,2018-10-08,16,3.048611,0,0.000000,0,2.500000,2.500000,2.507176,2.500000,2.500000,0,0,0,2.500000,2.5,2.715972,2.500000,2.621019
41,NaN,2018-10-08,17,3.319167,0,0.000000,0,2.500000,2.500000,2.540972,2.500000,2.500000,0,0,0,2.500000,2.5,2.676620,2.500000,2.652407
42,NaN,2018-10-08,18,3.743889,0,0.000000,0,2.500000,2.500000,2.639583,2.500000,2.500000,0,0,0,2.500000,2.5,2.889583,2.500000,2.767083
43,NaN,2018-10-08,19,5.195370,0,0.000000,0,2.500000,2.500000,3.533611,2.500000,2.500000,0,0,0,2.500000,2.5,3.367639,2.500000,3.176296
44,NaN,2018-10-08,20,4.609120,0,0.000000,0,2.500000,2.500000,3.887639,2.500000,2.506065,0,0,0,2.500000,2.5,3.377870,2.500000,2.766620
45,NaN,2018-10-08,21,3.931389,0,0.000000,0,2.500000,2.500000,3.253472,2.500000,2.500000,0,0,0,2.500000,2.5,2.983194,2.500000,2.727037
46,NaN,2018-10-08,22,2.903611,0,0.000000,0,2.500000,2.500000,2.642685,2.500000,2.500000,0,0,0,2.500000,2.5,2.716852,2.500000,2.582963
47,NaN,2018-10-08,23,2.633519,0,0.000000,0,2.500000,2.500000,2.500000,2.500000,2.500000,0,0,0,2.500000,2.5,2.521389,2.500000,2.537083

In [4]:
df.keys()

Index(['Unnamed: 0', '_Date', '_Hour', 'DUAC_CCE utilization Cell (avg)',
       'DUAC_Cell Handover Rejection Rate',
       'DUAC_Cell RRC Connection Establishment Fail Rate',
       'DUAC_Cell RRC Connection Reestablishment Fail Rate',
       'DUAC_DL BB Cap utilization BB module (avg)',
       'DUAC_DL PRB BB mod (avg)', 'DUAC_DL PRB Cell (avg)',
       'DUAC_DL SE utilization BB module (avg)',
       'DUAC_DL SE utilization Cell (avg)', 'DUAC_Inc HO Rejects',
       'DUAC_RRC Conn Rejects', 'DUAC_RRC Reestab Rejects',
       'DUAC_UL BB Cap utilization BB module (avg)',
       'DUAC_UL PRB BB mod (avg)', 'DUAC_UL PRB Cell (avg)',
       'DUAC_UL SE utilization BB module (avg)',
       'DUAC_UL SE utilization Cell (avg)'],
      dtype='object')